### PR TITLE
Installed active storage

### PR DESCRIPTION
**Pull request by swpinchen**
Completed active storage installation steps:
https://www.douglasberkley.com/tutorials/activestorage_cloudinary.html
Not yet added to model.

### CODE REVIEW

**Comment by IvanReyesO7** [comment]
Seems ok to me

**Review by Natashakors — APPROVED** [review]

**Comment by Natashakors** [comment]
Good

**Review by Natashakors — COMMENTED** [review]
good

**Review by IvanReyesO7 — COMMENTED** [review]
Cool!

**Pull request merged**
